# Generated by Django 5.0.1 on 2024-01-12 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('account', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 12, 21, 36, 36, 422489), null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], default='male', max_length=20)),
                ('userimg', models.ImageField(null=True, upload_to='userimg/')),
            ],
        ),
    ]
