# Generated by Django 5.0.1 on 2024-01-21 15:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 21, 20, 47, 46, 728237), null=True),
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvetsMentType', models.CharField(choices=[('individual', 'Individual'), ('Common', 'Common')], default='individual', max_length=20)),
                ('InvetsMentCategory', models.CharField(choices=[('Equity', 'Equity'), ('Crypto', 'Crypto'), ('Mutual Fund', 'Mutual Fund'), ('Other', 'Other')], default='Equity', max_length=20)),
                ('Ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superusers.users')),
            ],
        ),
    ]
