# Generated by Django 5.0.1 on 2024-01-21 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superusers', '0002_alter_users_account_userrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='account',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 21, 20, 48, 2, 205261), null=True),
        ),
    ]
